Add BEGINNER/ADVANCED structure
zkSNACKs/WasabiDoc2 pull request #3
Opened 2021-12-18 07:47 UTC by BTCparadigm

If the [idea](https://github.com/zkSNACKs/WalletWasabi/discussions/6740#discussioncomment-1840029) is accepted, this PR creates few new files and folders to the 2.0 docs.

2021-12-18 08:37 UTC, nopara73 commented on docs/README.md
> +Even though we have tried to make our new software UI as intuitive as possible, we should still describe the functions of our wallet and explain the magic under the hood, so users can make better dec
software's

2021-12-18 08:39 UTC, nopara73 commented on docs/README.md
> +Even though we have tried to make our new software UI as intuitive as possible, we should still describe the functions of our wallet and explain the magic under the hood, so users can make better dec
- possession
- Don't use the word "new", it makes it obsolate fast

```suggestion
Even though we have tried to make our software's UI as intuitive as possible, we should still describe the functions of our wallet and explain the magic under the hood, so users can make better decisions regarding their financial privacy.

```

2021-12-18 08:44 UTC, nopara73 approved these changes

2021-12-18 08:44 UTC, BTCparadigm commented on docs/README.md
> +Even though we have tried to make our new software UI as intuitive as possible, we should still describe the functions of our wallet and explain the magic under the hood, so users can make better dec
What do you mean by "possession"?

2021-12-18 09:46 UTC, MarnixCroes commented
NACK
I thought we agreed to not separate into _beginner_ and _advanced_ at "main page".
f.e.: `send`can have _advanced_ aspects aswell

2021-12-18 11:28 UTC, BTCparadigm commented
I understood this idea is still WIP and the titles can be changed. I actually like Bitcoin-Pleb and Super Shadowy Coder levels even more than beginner/advanced :D
I dont know if there has been any other practical idea for the structure.

2021-12-18 12:55 UTC, yahiheb approved these changes
LGTM

2021-12-22 07:17 UTC, nopara73 requested changes
Concept NACK. It make no sense to make significant structural changes to the docs. This repository should be deleted.

2021-12-22 08:40 UTC, closed without merging